### ISSUE TITLE
IE doesn't support Array.prototype.indexOf, causing Squire to crash.

### ISSUE THREAD

**Issue by borestad** [iammerrick/Squire.js#18]
<pre>
magicModuleLocation = dependencies.indexOf(magicModuleName);
</pre>

...crashes the code in old IE's. 
Also, be careful with Array.prototype.splice.

Using a ES5-shim solves the problem, but it should probably be refactored anyway.

Thanks for a great library.
Johan

**Comment by iammerrick** [comment]
Thanks! How do you suggest refactoring this away from indexOf? You mean pulling in a compatible indexOf function and using that?

**Comment by borestad** [comment]
Hi!

Normally, you'd solve this by adding it to Array.prototype, but since this is a external library, that's not even an option imho.

Some helper util like this would probably be the fastest/best solution.

<code>
function index(array, value) {
    for(var i=0; i< array.length, item = array[i]; i++) {
        if (item === value) {
            return i;
        }  
    }
    return -1;
}
</code>

**Comment by iammerrick** [comment]
Yup I figured as such. Great! I'll get on this! Thanks!

**Comment by borestad** [comment]
No problem :)
While we're at it, be careful to iterate over objects like this:

<pre>
      for (alias in path) {
        this.mock(alias, path[alias]);
      }
</pre>

Use hasOwnProperty instead to ensure that you really get the keys you want (if some library has altered Object.prototype)

<pre>
      for (alias in path) {
        if (path.hasOwnProperty(alias) ) {
          this.mock(alias, path[alias]);  
        }        
      }
</pre>

**Comment by iammerrick** [comment]
Did a general refactor that ought to have done a while ago. Let me know if it helps you out. :-)
