### ISSUE TITLE
Add in npm or bower registry

### ISSUE THREAD

**Issue by anacronw** [iammerrick/Squire.js#25]
Have you considered adding squire.js in the npm registry?  I realize this project is specifically for the browser, but Isaac Schlueter had stated openly that he actually prefers that browser components be in npm: http://blog.izs.me/post/27987129912/tj-holowaychuk-components

**Comment by iammerrick** [comment]
Would love to add it to these things. Thanks for the reminder.

**Comment by wookiehangover** [comment]
+1

**Comment by tedeling** [comment]
+1

**Comment by iammerrick** [comment]
Done: https://github.com/iammerrick/Squire.js#installation 

Thanks for the input :-).

M
