### ISSUE TITLE
Proper Deps Support

### ISSUE THREAD

**Issue by iammerrick** [iammerrick/Squire.js#3]
Support deps in data-main and config.

See: https://github.com/iammerrick/Squire.js/pull/2

**Comment by iammerrick** [comment]
Also... https://gist.github.com/404e01389ca1e47bcab0#comments

**Comment by rmurphey** [comment]
@iammerrick re your question about how i'm using deps ... https://gist.github.com/404e01389ca1e47bcab0#file_config.js is a good example. In this example, I use the same config as I use for my app, and use `deps` to load a different bootstrapping file depending on whether I'm in testing land or not. If I am in testing land, then that bootstrapping file looks like this:

```
(function() {

// test mode -- 'tdd', 'bdd-should', or 'bdd-expect'
var mode = 'tdd';

if ( mode === 'tdd' ) {
  window.assert = chai.assert;
}

if ( mode === 'bdd-should' ) {
  window.should = chai.should();
}

if ( mode === 'bdd-expect' ) {
  window.expect = chai.expect;
}

mocha.setup({
  ui: mode.split('-')[0],
  globals: [ 'XMLHttpRequest' ]
});

require( [ 'list_of_tests' ], function( lot ) {
  require( lot, function() {
    mocha.run();
  });
});

}());
```

For what it's worth, this config (and the gist linked above) is for a demo for a class I teach ... I'm not 100% sure I'd do it this way in The Real World, but I do think it's a reasonable enough use case :)

**Comment by jaredwy** [comment]
My use case is simply telling require where to load its config file from. This sets as the dep propert, the loaded file. This is then attempted to be loaded each time you create a new test context. 
Did not realise you could set deps from that config file.

Although, i am not convinced that a mocking framework should be attempting to load any deps that are not explicitly allowed?

@rmurphey with squire does your need for a seperate bootstrap for test/prod go away?

**Comment by rmurphey** [comment]
@jaredwy regardless of Squire, I still need different bootstrapping for this project -- in testing land, I want to run the tests, while in application land, I want to run the application. I want to do both from the same config file, because I want to avoid having duplicated configs.

**Comment by rmurphey** [comment]
The entire app in question is [here](https://github.com/rmurphey/testable-javascript/tree/refactored_with_tests).

**Comment by jaredwy** [comment]
Cool, was unsure of your approach to testing. That app answers my questions.
I will take another look at my fix to get it working with deps defined in the config while still ignoring the dep defined in the data-main. 

(as an aside javascript really needs a fixture loading lib)

**Comment by iammerrick** [comment]
So the trouble in using the deps property like this is that every time you copy the configuration and create a new context require.js attempts to load the all the deps. @jaredwy  fix essentially says "don't load this cause I've already loaded it and applied it to the very configuration you are using". Squire.js could copy all the loaded modules into its own context's cache and that would prevent it from loading the dependencies each time. That comes with its own set of problems. With Jared's fix you could easily do this...

``` html
<script src="require.js" data-main="config.js"></script>
```

``` javascript
requirejs.config({
  baseUrl: '../src',
  paths: {
    tests: '../test/tests',
    mocks: '../test/mocks'
  }
});

 mocha.setup('bdd');
 chai.should();

 require(['tests/SquireTests'], function() {
   mocha.run();
 });
```

The problem is when you use the deps property the expectation is that those will be loaded _for each context_. Its ok in the case of configuration because we copy those over when you create a new squire anyhow. Other modules its harder... 

Thoughts? Also @jaredwy sorry I've been so MIA. Maybe we could set up a time to skype (I'm jabber all the time though.) skype is less usual for me.

M

**Comment by jaredwy** [comment]
The modules defined in require were an unknown to me. I am still not sure how you should be dealing with them. I hopefully will get some time over the christmas break to take another stab at it. It could be fixed if require did not treat the config as a dep but added it as a new property off the context. This would then limit squire working with newer versions of require though.

I tried to add you to gchat but did not seem to go through? Perhaps you can add me on jared.wyles @ gmail dot com see if that works?

**Comment by iammerrick** [comment]
Excuse me @rmurphey would you be so kind to fork this and break it? https://github.com/iammerrick/Squire.js/blob/master/test/tests-with-main.html I seem to able to run a simplified version of your setup just fine with the patch from @jaredwy.

**Comment by rmurphey** [comment]
Agree that with @jaredwy's patch my setup will run just fine. There's still the incredibly weird issue that I laid out [here](https://gist.github.com/404e01389ca1e47bcab0) but I don't think it's related to the deps stuff.

**Comment by iammerrick** [comment]
Awesome. I will look closer at that exact case. Its unfortunate that Squire.js is in the business of wrapping require.js. One of the main goals is to provide this functionality without overriding the require.js behavior. Ultimately my hope is that James Burke will take notice and try to pitch in on getting a really solid DI layer into Require.js or at least as a side project to be used in collaboration with it much like Squire.js. :-)

**Comment by rmurphey** [comment]
I wouldn't spend too much time on that exact case unless you're really bored :) Mostly wanted to get it documented because it was so incredibly weird. Thanks for following up on the deps stuff though!

**Comment by iammerrick** [comment]
No problem, thanks for giving Squire.js a go. I hope you find it useful. :-)
