### ISSUE TITLE
Needs further documentation/usage examples

### ISSUE THREAD

**Issue by singingwolfboy** [iammerrick/Squire.js#32]
Squire.js looks like just what I need for mocking require.js dependencies in my tests, but I don't understand how to use it properly. Can you put together some documentation on how to get started using it? Some examples would be great, particularly with the jasmine test framework. Even just a blog post would be helpful!

**Comment by iammerrick** [comment]
This sounds like an incredibly reasonable request. :-)

**Comment by Dakuan** [comment]
@singingwolfboy I will be doing a write up on coderwall soon I hope!

**Comment by iammerrick** [comment]
Thanks. Pull requests welcome. :-)
