### ISSUE TITLE
With Jasmine.js Tests Run Always Positive No Matter What Inside the Mock Function

### ISSUE THREAD

**Issue by Millad** [iammerrick/Squire.js#4]
I'm using Require.js to use AMD in my project. I use it in my project and in my Jasmine tests with no problems.

I'm using Squire.js to mock my DAO classes in my Services. When I expect the test to fail in a simple as a true to be false, the test should fail but it does not fail. Even expect 2 to be 3 runs positive and green but only inside the require space like so:

define(
[
"Squire",
"DAO/MockUserDAO"
],
function(Squire,MockUserDAO){
describe("UserService",function(){

```
    it("should return an array of  4 users on getAll()",function(){

        var squire = new Squire();

        squire.mock(["DAO/UserDAO"],MockUserDAO)
            .require(["services/UserService"], function(UserService){
                        var userCount = UserService.getAll().length;
                        expect(2).toBe(1);  // DOES NOT FAIL!
                    }); 

    });

    it("should return true",function(){
        expect(true).toBe(false);  // FAILS as expected
    });


}); 
```

}

**Comment by iammerrick** [comment]
Squire.js needs to download your file "services/UserService" so your expect is essentially being run long after jasmine has decided the test positive. If you want to leverage squire inside of an it block like this you need to make it asynchronous. 

[Asynchronous Spec](https://github.com/pivotal/jasmine/wiki/Asynchronous-specs)

I'd recommend abstracting that painful polling with this [mocha style async](https://github.com/derickbailey/jasmine.async).

M

**Comment by Millad** [comment]
Thanks alot, it worked when using jasmine.async.

**Comment by anacronw** [comment]
I am having the same issue with mocha.  I can't find a good place to defer the execution of my mocha specs until after the specs have been defined from within the squire's injector.require block.

For mocha, do you recommend using squire from within the asynchronous specs?  Something like:

``` javascript
  describe('some suite', function(){
    it('should wait until squire is done loading before executing the spec', function(done){
      injector.require(['moduleToTest'], function(moduleToTest){
      // do whatever tests need to do here
        done();
      }
    });
  })
```

**Comment by anacronw** [comment]
ahh, slightly more elegantly (by doing the injection asynchronously through the before block):

``` javascript
  var module;
  describe('some suite', function(){
    before(function(done){
      injector.require(['moduleToTest'], function(moduleToTest){
        module = moduletoTest
        done();
      }
    });
    it('now these tests can be run without done', function(){
      //hurray
    });
  })
```

This works for me ;)  Your feedback is still appreciated.

**Comment by joeeames** [comment]
@badunk 
All the design and implementation of SquireJS has been centered around the first use case, basically embedding the injector.require inside of your test, or in this case the it function.

The only drawbacks I can see at this time with your idea to put it into the before function would be the fact that any mocks that you want set up have to be done before the inject call.  so essentially you are stuck with the same mock implementations for all dependencies for every test inside of that containing describe.  That means that you will end up likely creating a lot more describes to allow for variations in the mocked dependencies.  This isn't necessarily bad, and how much this truly affects you will vary from one set of tests to the next.

The benefit is that even though your before is a bit uglier, your test is now much prettier.  If this works for you I would continue to use it.
