### ISSUE TITLE
Why require wrapping mock functions in functions?

### ISSUE THREAD

**Issue by kbaltrinic** [iammerrick/Squire.js#40]
First I want to say that now that I am getting the hang of the API, I am finding Squire very useful.

That said, I did find the mock() API unduly confusing at first and wanted to make some recommendations.  

The reason for the existence of the two helper methods documented at the end of the readme escaped me for a while.  After looking at Squire's unit tests, I finally came to the understanding that what one passes to mock() is exactly what a regular module would pass as the final argument to define().  In other words, it can be an object or a function, but if it is a function, Require will assume it is is a factory that returns the real value.  

In the case of define, this makes sense, because the function can accept arguments, namely any dependencies that were declared in the second argument to define().  However, in Squire there is presently no way for any dependencies to be passed to the  function.  So what value has it as a factory?  It seems to me that any code that it might execute beyond returning the mock could be executed in the enclosing closure.  This in turn negates the value of any implementation of the factory other than the one that just returns the mock.

If this is indeed the case, why doesn't mock just automatically wrap its second argument in a function and be done with it?  Even if the value were not a function, wrapping it in one would have no effect on Require that I am aware of.  If I am wrong, mock could conditionally wrap the argument only if it is a function.  This would make the API a lot less confusing.

This cause quite some consternation when I was first trying to use Squire to mock a class function (constructor) , overriding the original class definition.  The fact that I had to pass new function(){ return MyMockClass; } instead of just MyMockClass to mock was dumbfounding for a while, especially in light of the documentation for the mock method: "the second argument is _the mock itself_" [emphasis added].  

At the very least the documentation for mock needs to be improved on this point.  Alternatively, I would prefer having mock wrap functions automatically.  If we do want to leave the possibility open for meaningful factory functions, maybe add an optional argument to mock that is an array of dependency names to pass to the factory method, in the pattern of define(), and only auto-wrap if said argument is undefined.

Just some thoughts...

**Comment by iammerrick** [comment]
Hey thank you for the thoughts, and now that you mention it, I suppose you are right there is no real value to having a factory function. It's funny because I just closed an issue regarding this. I will look at an API change.

**Comment by kbaltrinic** [comment]
Glad to be of help.  Sorry I did not realize this was a duplicate of #38.  I should have just added to that one.  In any event, I would recommend updated the documentation to remove/deprecate the helper method.  Otherwise, if people keep using it, they will now have doubly wrapped functions.  Not a functional issue but it could be confusing.

**Comment by c24w** [comment]
Hello,

We've just upgraded to the latest Squire and came across this breaking change.  Whilst we agree that the `mock` API is a bit confusing to begin with,  I'm afraid we disagree with the case put forward by @kbaltrinic because it now behaves _less_ like `define` in RequireJS.  The factory function has proven useful for testing in the following way, for example:

```
it('loads the HTML 5 shiv', function (done) {
    var shivLoaded;
    squire.mock('html5shiv', function () {
        shivLoaded = true;
    })
    .require(['app'], function () {
        expect(shivLoaded).to.be.true;
        done();
    });
});
```

Now we are stuck for a way to write such tests.  We think improving the API documentation would be more beneficial than losing this functionality.

**Comment by kbaltrinic** [comment]
Perhaps a good compromise would be an additional method on Squire to handle the different behavior.  I still feel that mock should accept a mock directly; thats the meaning of the term.  But perhaps a Squire.define(…) method could be added to support the original behavior? Or Squire.mockCallback(…).  Or per my original recommendation, add an overload to mock, though for @c24w's particular scenario, that approach is a bit cumbersome.

**Comment by actionshrimp** [comment]
Squire.defineMock ?

**Comment by kbaltrinic** [comment]
That could work too.  I think finding a really good self-explanatory method name is going to be tough given the domain, my vote is to just pick something reasonable and then make sure the documentation is crystal clear on the difference between the methods.

**Comment by iammerrick** [comment]
I like .define as it is intended to defer to the nested require's define directly.

**Comment by c24w** [comment]
That works for me!
