### ISSUE TITLE
Add tags so that versioning can be used when fetching Squire with bower

### ISSUE THREAD

**Issue by pajtai** [iammerrick/Squire.js#43]
http://bower.io/#registering-packages

> Your package should use semver Git tags.

**Comment by jroper** [comment]
+1

I would like to create a webjar for squire (http://webjars.org), we usually point at a git tag to generate the webjar, with no tags in git, we can't create a webjar.

**Comment by iammerrick** [comment]
Done. Thanks for the bump @jroper

**Comment by jroper** [comment]
No worries, thanks for fixing so quickly!
