### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by AndreasPresthammer** [iammerrick/Squire.js#5]
Hi!
Have you considered hosting your project as a Nuget package?

**Comment by iammerrick** [comment]
Turns out I don't know anything about .NET or the Microsoft world in general. How would I best explore that road?

M

**Comment by joeeames** [comment]
We can chat about it tomorrow.

On Tue, Jan 1, 2013 at 9:52 PM, Merrick Christensen <
notifications@github.com> wrote:

> Turns out I don't know anything about .NET or the Microsoft world in
> general. How would I best explore that road?
> 
> M
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iammerrick/Squire.js/issues/5#issuecomment-11800217.

## 

Joe Eames
Software Craftsman

**Comment by iammerrick** [comment]
Perhaps someone will pull request the ability to do this.
