### ISSUE TITLE
Support mocks of RequireJs plugins called with require()

### ISSUE THREAD

**Issue by talkol** [iammerrick/Squire.js#62]
Plugins such as https://github.com/requirejs/text are usually used with `require()`

```
require(["text!some/module.html", "text!some/module.css"], function(html, css) {
    // loaded here
});
```

Since this is not a traditional `define()` dependency, the Squire mocks are ignored in this case.

See this fiddle project for a full example:
http://runnable.com/VUBoI0ex6v9Gs-BJ/squirejs-with-plugins-for-node-js-and-hello-world

**Comment by LeopoldoFu** [comment]
So how do we mock require plugins with squire?  I'm trying to get it to work with [require-is](https://github.com/guybedford/require-is)
