### ISSUE TITLE
storing mocks with directory paths

### ISSUE THREAD

**Issue by anacronw** [iammerrick/Squire.js#7]
when I tried the following, I didn't get mocks back:

``` javascript
    injector
        .store('directory/module')
        .require('someOtherModule', function(someOtherModule, mocks){
            console.log(mocks); // it returns undefined
        });
```

Something I'm doing wrong?  Should mocks have a property named 'directory/module' in this case?

**Comment by iammerrick** [comment]
Does someOtherModule depend on directory/module?

**Comment by iammerrick** [comment]
Also you need to tell it you want it like any other require.js magic module (think module, and async require).

``` javascript
   injector
        .store('directory/module')
        .require(['someOtherModule', 'mocks'], function(someOtherModule, mocks){
            console.log(mocks); // it returns undefined
        });
```

**Comment by anacronw** [comment]
Sorry, that was it - I didn't pass in the 'mocks' dependency.

However, I did get back an object with a "mocks" and "store" properties:

``` javascript
{
  mocks:{},
  store:{
    'directory/module' : {}
  }
}
```

I think the README is a little misleading in that regard with the line:

``` javascript
    // mocks.CrazyCalculatorDependency is the Calculators dependency, you can
```

since its technically in mocks.store

**Comment by iammerrick** [comment]
Thanks!
