### ISSUE TITLE
Squire Mock with CanJS

### ISSUE THREAD

**Issue by Millad** [iammerrick/Squire.js#8]
When mocking a module that has a dependency to canJS, I get the following error: Uncaught TypeError: Cannot read property 'setup' of undefined. If I remove canJS as depedency marked as "can" it works.

```
  // Code: simple object having a dependency to CanJS
  define(["can"],function(can){ return {id = 1}; }); 

 // Test
 define(
   [
    "Squire",
    "DAO/MockWebsiteDAO"
  ],
function(Squire,MockWebsiteDAO){
    describe("WebsiteControllerTest",function(){  
        var async = new AsyncSpec(this);

        async.it("should return all websites as an array",function(done){
            var squire = new Squire();
            squire.mock(["DAO/WebsiteDAO"],MockWebsiteDAO).require(["controllers/TestController"], function(TestController){
                            // fails because of the canJS dependency in TestController
                            done();
                        });  


        });

    }); 
```

});

trace:

can.Control.can.Construct._isAction control.js:95
can.Control.can.Construct.setup control.js:63
can.extend.extend construct.js:165
can.Construct construct.js:21
(anonymous function) control.js:43
j.execCb require.js:28
W.check require.js:18
(anonymous function) require.js:22
(anonymous function) require.js:8
(anonymous function) require.js:23
x require.js:7
W.emit require.js:23
W.check require.js:19
(anonymous function) require.js:22
(anonymous function) require.js:8
(anonymous function) require.js:23
x require.js:7
W.emit require.js:23
W.check require.js:19
(anonymous function) require.js:22
(anonymous function) require.js:8
(anonymous function) require.js:23
x require.js:7
W.emit require.js:23
W.check require.js:19
(anonymous function) require.js:22
(anonymous function) require.js:8
(anonymous function) require.js:23
x require.js:7
W.emit require.js:23
W.check require.js:19
(anonymous function) require.js:22
(anonymous function) require.js:8
(anonymous function) require.js:23
x require.js:7
W.emit require.js:23
W.check require.js:19
W.enable require.js:22
W.init require.js:16
D require.js:14
j.completeLoad require.js:27
j.onScriptLoad require.js:29

**Comment by iammerrick** [comment]
What does test controller look like?

**Comment by Millad** [comment]
I just found the problem. First, the above code works if only _one_ test that tests a CanJS controller is added with Squire. If you have multiple tests testing a CanJS controller it will cause this error: Uncaught TypeError: Cannot read property 'setup' of undefined. Printed In console.

So basically,  If you have two CanJS controller Tests that are used via Squire, the tests _fails_.

Is this a Squire issue? because many tests work when only declaring CanJS controllers without Squire.

If you want to study the simple code, I have it here, please look at the _test_ folder for my tests. I have tried to comment the problem in my script area in folder _test_ and file _index.html_, where the Jasmine _specs_ are included. Please note that the JS project is very small.
. 
https://github.com/Millad/Ve/tree/master/public/javascripts

**Comment by joeeames** [comment]
One of the things that jumps out at me as I glance at your specs is that you are "require-ing" in your mock.  So let's take for example UserServiceTest.js.  you require 'DAO/MockUserDAO' in that test.  Because of that you only have 1 instance of the MockUserDAO that is shared among all the tests.  is it possible that the first test is manipulating this object that then pollutes it when the second tests tries to run?

The typical pattern in unit tests is to strive for absolutely fresh state from test to test.  That assures that no previous test is polluting your state for a later test which can be an extremely  difficult problem to solve.  I don't know if that is the issue but would it be possible for you to eliminate this as the cause of the problem?

**Comment by Millad** [comment]
Thank you for your reply Joe, you are completely correct! I have edited the tests so that I have a absolutely fresh state from test to test. But it still fails with error in console when testing more than one CanJS controller with Squire.

**Comment by joeeames** [comment]
So I was right but not helpful....

The problem you're having just screams it's a state issue in testing, but other than that mock, I can't see how your state can possibly bleed over from one test to the next....

I'll try to fork your repo and see if the issue jumps out at me.

**Comment by Millad** [comment]
I think the problem is in  _jasmine.async_, I'm not 100% sure.I do not know how to work around the problem yet. Other tests that does not use CanJS run fine with async.Awaiting confirmation and help.

**Comment by joeeames** [comment]
it's super simple to switch to mocha for just a check to see if that's the problem.

**Comment by Millad** [comment]
I just switched to Mocha, and the first thing I get when using Squire is _Error: global leaks detected: can, Scanner_. Check out the basic code below please.

```
define(
[
  "Squire"
],
function(Squire){
    describe("HelloWorldController", function(){
          it("should have id #helloworld",function(done){
                var squire = new Squire();

                squire.require(["DAO/MockUserDAO"],function(MockUserDAO){

                  squire.mock(["DAO/UserDAO"],MockUserDAO).require(["controllers/HelloWorldController"], function(HelloWorldController){
                    assert(1==1);
                    done();
                  });

                });
                }); 
        }); 
});                       
```

**Comment by Millad** [comment]
By Adding the following to Mocha's globals, the tests run successfully, does this look good? 

```
 mocha.globals([ '$','jQuery','can','Scanner' ]) // acceptable globals
                .run();   
```

**Comment by joeeames** [comment]
yeah, I was going to point you at docs on turning that off.  What weirds me out is that it doesn't work in jasmine, but does in mocha.  I know that mocha is much better for async support than jasmine, but still, it's strange that it doesn't actually work in jasmine.

But unless you're stuck on using jasmine (I honestly recommend mocha) then I would go with mocha and call it good.  Not helpful that we don't understand why jasmine was bombing though.

**Comment by Millad** [comment]
By using Require, you automaticyl get globals when requiring jQuery and Can, but when requiring Squire I get this object as global: Scanner. This is strange.

**Comment by Millad** [comment]
Btw I'm still getting _"Uncaught TypeError: Cannot read property 'setup' of undefined"_ from CanJS Controller using Mocha with Squire. Is this a Squire issue or CanJS, I'm not sure. It happens only when Squire requires a CanJS Controller.

**Comment by joeeames** [comment]
I fat fingered the close button, sorry.  I reopened it.

Is the github repo you referenced in this thread up to date with mocha and reproducing the current problem?

**Comment by Millad** [comment]
No, I made a sample project. Please note the console output when running the tests. If you modify the test please clean the browser catch before rerunning the unit tests. I think Squire has a problem with CanJS.
I uploaded the project for you on dropbox.
http://dl.dropbox.com/u/55863157/Mocha_Testing_Ground.zip

**Comment by Millad** [comment]
Same problem in QUnit. The problem occurs when using squire to require two or more CanJS Controllers.

**Comment by joeeames** [comment]
Keep working on it.  I'll try to look at it when I can.
